// Generated by decopin build. Edits are overwritten on the next build.

import { run } from 'decopin-cli';
import {
  envFile,
  globalError,
  helps,
  notFound,
  routes,
  versionFile,
} from './routes.ts';

// Ctrl+C is 128+2 = 130. Without a handler Bun would exit with 0
process.on('SIGINT', () => process.exit(130));

// No top-level await on purpose: bun build --compile --bytecode refuses a
// module that has one, and bytecode is worth about a fifth of startup
// (11.0ms vs 13.8ms measured). run() reports failures itself, so the
// rejection path here only catches bugs in the framework.
run(routes, {
  program: "ecs-pf",
  bin: "ecs-pf",
  globalError,
  notFound,
  helps,
  envFile,
  versionFile,
}).then(
  (code) => process.exit(code),
  (error) => {
    process.stderr.write(String(error) + '\n');
    process.exit(1);
  }
);
