// Generated by decopin build. Edits are overwritten on the next build.

import type { RouteTable } from 'decopin-cli';

export const routes = {
  "connect": {
    command: () => import("../app/connect/command.tsx"),
    argv: () => import("../app/connect/argv.tsx"),
    effects: {"fs.read":"detected","fs.write":"detected","network":"detected","process.spawn":"detected","process.mutate":"detected"},
  },
  "enable-exec": {
    command: () => import("../app/enable-exec/command.tsx"),
    argv: () => import("../app/enable-exec/argv.tsx"),
    effects: {"fs.read":"detected","fs.write":"detected","network":"detected","process.spawn":"unknown","process.mutate":"detected"},
  },
  "exec": {
    command: () => import("../app/exec/command.tsx"),
    argv: () => import("../app/exec/argv.tsx"),
    effects: {"fs.read":"detected","fs.write":"detected","network":"detected","process.spawn":"detected","process.mutate":"detected"},
  },
} satisfies RouteTable;

export const helps: Record<string, () => Promise<unknown>> = {};

export const globalError = () => import("../app/global-error.tsx");
export const notFound = undefined;
export const envFile = undefined;
export const versionFile = () => import("../app/version.tsx");
