// Generated by decopin build / decopin dev.
// Edits are overwritten on the next build.

import 'decopin-cli';

declare module 'decopin-cli' {
  interface Routes {
    "connect": { args: {}; options: { region?: string; cluster?: string; task?: string; rds?: string; "rds-port"?: number; "local-port"?: number }; stdin: never; data: never };
    "enable-exec": { args: {}; options: { region?: string; cluster?: string; service?: string }; stdin: never; data: never };
    "exec": { args: {}; options: { region?: string; cluster?: string; task?: string; container?: string; command?: string }; stdin: never; data: never };
  }
}
