name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  lint-and-build:
    name: Lint and Build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Run TypeScript type check
        run: bun run type-check

      - name: Run Biome format check
        run: bun run format:check

      - name: Run Biome lint
        run: bun run lint

      - name: Run Biome check (combined)
        run: bun run ci

      - name: Build project
        run: bun run build

      - name: Check build output
        run: |
          if [ ! -f "dist/cli.js" ]; then
            echo "Build failed: dist/cli.js not found"
            exit 1
          fi
          echo "Build successful: dist/cli.js exists"

      - name: Test executable
        run: |
          if [ -x "dist/cli.js" ]; then
            echo "dist/cli.js is executable"
          else
            echo "dist/cli.js is not executable"
            exit 1
          fi

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: dist/
          retention-days: 30
