name: CI

on:
  push:
  pull_request:

jobs:
  lint-and-build:
    name: Lint and Build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [24.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run TypeScript type check
        run: npm run type-check

      - name: Run Biome check (format + lint + organize imports)
        run: npm run check:dry

      - name: Run Biome CI optimized check
        run: npm run ci

      - name: Build project
        run: npm run build

      - name: Run tests
        run: npm run test

      - name: Check build output
        run: |
          if [ ! -f "dist/cli.js" ]; then
            echo "Build failed: dist/cli.js not found"
            exit 1
          fi
          echo "Build successful: dist/cli.js exists"

      - name: Test executable
        run: |
          if [ -x "dist/cli.js" ]; then
            echo "dist/cli.js is executable"
          else
            echo "dist/cli.js is not executable"
            exit 1
          fi

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: dist/
          retention-days: 30
